version: '3'
services:
  matilda:
    build:
      context: ./web
      dockerfile: Dockerfile.lida
    ports: 
      - "5000:5000"
    network_mode: "host"
    image: mastrogeppetto/dockerlida:latest
  mongodb:
    image: mongo:bionic
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./configdb:/data/configdb
      - ./db:/data/db
    network_mode: "host"
  nginx:
    image: nginx
    ports: 
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    network_mode: "host"

